name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub profile 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Usando o PAT
          USERNAME: "PeterAbenza"  # Adicione o seu nome de usuário do GitHub aqui

      - name: Commit & Push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A .
          git commit -m "Generated 3D Contribution Graph" || echo "No changes to commit"
          git push
