name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Roda todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub profile 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.6.0

      - name: Commit & Push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A .
          git commit -m "Generated 3D Contribution Graph" || echo "No changes to commit"
          git push
